###################################################################################
#
# For use on production server.
# compose.production.yaml is to be used in conjunction with compose.yaml
# > docker compose -f compose.yaml -f compose.production.yaml up -d
#
###################################################################################

services:
  # redirect:
  #   # Temporary redirect of main page, quick way to disable access.
  #   image: morbz/docker-web-redirect
  #   ports:
  #     - 8888:80
  #   restart: always
  #   environment:
  #     - REDIRECT_TARGET=https://www.cmu.edu/dietrich/english/research-and-publications/myprose.html
  #     - REDIRECT_TYPE=redirect
  mongo:
    volumes:
      - db_data:/data/db

  ontopic:
    ports: !reset []

  frontend:
    # ports: !reset [] # use if redirect is enabled
    environment:
      # ANTHROPIC_MODEL: claude-3-7-sonnet-20250219
      LTI_HOSTNAME: https://docuscope-sc.eberly.cmu.edu/
    volumes:
      - "/srv/scribe/myprose-resources:/app/resources:ro"

volumes:
  db_data:
    labels:
      edu.cmu.eberly.docuscope.description: "Database volume"
