###################################################################################
#
# A copy of docker-compose.yml with added mounting of the `settings` directory
# so that features and options can be changed without needing to recompile.
#
###################################################################################

version: '3'
services:
  db:
    image: docker.io/mysql:8
    restart: always
    secrets:
      - db_root_password
      - db_user
      - db_password
    environment:
      MYSQL_DATABASE: dswa
      MYSQL_ROOT_PASSWORD_FILE: "/run/secrets/db_root_password"
      MYSQL_USER_FILE: "/run/secrets/db_user"
      MYSQL_PASSWORD_FILE: "/run/secrets/db_password"
    volumes:
      - db-data:/var/lib/mysql

  mongo:
    image: docker.io/mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME_FILE: "/run/secrets/mongo_user"
      MONGO_INITDB_ROOT_PASSWORD_FILE: "/run/secrets/mongo_pass"
    secrets:
      - mongo_user
      - mongo_pass

  ontopic:
    build:
      context: ./ontopic
      dockerfile: ./Dockerfile
    restart: always
    #ports:
    # - 5000:5000

  frontend:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    ports:
     - 8888:8888
    secrets:
      - db_user
      - db_password
      - mongo_user
      - mongo_pass
      - openai_api_key
      - token
    environment:
      ONTOPIC_SERVER: http://ontopic:5000/
      LTI_HOSTNAME: https://docuscope-sc-test.eberly.cmu.edu/
      LTI_KEY_FILE: /run/secrets/token
      MYSQL_HOST: db
      MYSQL_PORT: 3306
      MYSQL_DATABASE: dswa
      MYSQL_USER_FILE: /run/secrets/db_user
      MYSQL_PASSWORD_FILE: /run/secrets/db_password
      TOKEN_SECRET_FILE: /run/secrets/token
      OPENAI_API_KEY_FILE: /run/secrets/openai_api_key
      SCRIBE_TEMPLATES: /app/build/app/settings/templates.json
      PORT: 8888
      MONGO_HOST: mongo:27017
      MONGO_DB: doscuscope
      MONGO_USER_FILE: /run/secrets/mongo_user
      MONGO_PASSWORD_FILE: /run/secrets/mongo_pass
      NODE_ENV: production
    restart: always
    depends_on:
      - "db"
    volumes:
      - "./settings:/app/build/app/settings:ro"

volumes:
  db-data:
    labels:
      edu.cmu.eberly.docuscope.description: "Database for DocuScope Write & Audit Scribe"

secrets:
  db_user:
    file: secrets/db_user
  db_password:
    file: secrets/db_password
  db_root_password:
    file: secrets/db_root_password
  mongo_user:
    file: secrets/mongo_user
  mongo_pass:
    file: secrets/mongo_pass
  openai_api_key:
    file: secrets/openai_api_key
  token:
    file: secrets/token
