###################################################################################
#
# For use in development environment.
# docker-compose.yml with added mounting of the `settings` directory
# so that features and options can be changed without needing to recompile.
#
###################################################################################

services:
  mongo:
    image: docker.io/mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME_FILE: "/run/secrets/mongo_user"
      MONGO_INITDB_ROOT_PASSWORD_FILE: "/run/secrets/mongo_pass"
    secrets:
      - mongo_user
      - mongo_pass

  ontopic:
    build:
      context: ./ontopic
      dockerfile: ./Dockerfile
    restart: always
    ports:
     - 5000:5000

  frontend:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    ports:
     - 8888:8888
    secrets:
      - anthropic_api_key
      - mongo_user
      - mongo_pass
      - openai_api_key
      - token
    environment:
      ANTHROPIC_API_KEY_FILE: /run/secrets/anthropic_api_key
      ANTHROPIC_MAX_TOKENS: 2048
      EXPIRE_REVIEW_SECONDS: 86400
      LTI_HOSTNAME: https://docuscope-sc-test.eberly.cmu.edu/
      LTI_KEY_FILE: /run/secrets/token
      MONGO_DB: doscuscope
      MONGO_HOST: mongo:27017
      MONGO_PASSWORD_FILE: /run/secrets/mongo_pass
      MONGO_USER_FILE: /run/secrets/mongo_user
      NODE_ENV: production
      ONTOPIC_SERVER: http://ontopic:5000/
      OPENAI_API_KEY_FILE: /run/secrets/openai_api_key
      PORT: 8888
      SCRIBE_TEMPLATES: /app/private/templates.json
      TOKEN_SECRET_FILE: /run/secrets/token
      WRITING_TASKS: /app/private/writing_tasks
    restart: always
    depends_on:
      - "mongo"
    volumes:
      - "./settings:/app/build/app/settings:ro"
      - "./private:/app/private:ro"

secrets:
  anthropic_api_key:
    file: secrets/anthropic_api_key
  mongo_user:
    file: secrets/mongo_user
  mongo_pass:
    file: secrets/mongo_pass
  openai_api_key:
    file: secrets/openai_api_key
  token:
    file: secrets/token
