###################################################################################
#
#
#
###################################################################################

version: '3'
services:

  dswadb:
    image: mysql:8.0.30
    #image: mysql:5.7.22
    # We don't need an externally exposed port since docker-compose makes 3306 available 
    # to it's own private network anyway. However it is very helpful for testing
    ports:
     - 13306:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD} 
      MYSQL_DATABASE: ${MYSQL_DATABASE} 
      MYSQL_USER: ${MYSQL_USER} 
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./dswadb:/var/lib/mysql 
    user: ${MYSQL_UID}
