###################################################################################
#
#
#
###################################################################################

version: '3'
services:

  dswadb:
    image: mysql:8.0.30
    # We don't need an externally exposed port since docker-compose makes 3306 available 
    # to it's own private network anyway. However it is very helpful for testing
    ports:
     - 33306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 4570WK821X6OiyT508srN09wI
      MYSQL_DATABASE: dswa
      MYSQL_USER: dswa
      MYSQL_PASSWORD: 4570WK821X6OiyT508srN09wV
      #MYSQL_TCP_PORT: 4307
    volumes:
      - ./dswadb:/var/lib/mysql 
    user: ${MYSQL_UID}

  dswa-ontopic:
    build:    
      context: ./ontopic
      dockerfile: ./Dockerfile    
    ports:
     - 5000:5000
    tty: true
    stdin_open: true

  dswa-frontend:
    build:    
      context: ./frontend
      dockerfile: ./Dockerfile
    ports:
     - 8888:8888
    environment:
      DSWA_ONTOPIC_HOST: "dswa-ontopic"
      DSWA_ONTOPIC_PORT: 5000
    tty: true
    stdin_open: true
    depends_on:
      - "dswadb"    
    