###################################################################################
#
# For use on production server.
# docker-compose-production.yml with added mounting of the `settings` directory
# so that features and options can be changed without needing to recompile.
#
###################################################################################

services:
  # redirect:
  #   # Temporary redirect of main page.
  #   image: morbz/docker-web-redirect
  #   ports:
  #     - 8888:80
  #   restart: always
  #   environment:
  #     - REDIRECT_TARGET=https://www.cmu.edu/dietrich/english/research-and-publications/myscribe.html
  #     - REDIRECT_TYPE=redirect
  mongo:
    image: docker.io/mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME_FILE: "/run/secrets/mongo_user"
      MONGO_INITDB_ROOT_PASSWORD_FILE: "/run/secrets/mongo_pass"
    secrets:
      - mongo_user
      - mongo_pass
    volumes:
      - db_data: /data/db

  ontopic:
    image: ghcr.io/cmueberlycenter/eberly-docuscope-wa/ontopic:latest
    restart: always
    volumes:
      - "./ontopic/data:/home/appuser/data:ro"
      - "./ontopic/resources:/home/appuser/resources:ro"

  frontend:
    image: ghcr.io/cmueberlycenter/eberly-docuscope-wa/myprose:latest
    ports:
     - 8888:8888
    secrets:
      - anthropic_api_key
      - mongo_user
      - mongo_pass
      - openai_api_key
      - token
    environment:
      ANTHROPIC_API_KEY_FILE: /run/secrets/anthropic_api_key
      LTI_HOSTNAME: https://docuscope-sc.eberly.cmu.edu/
      LTI_KEY_FILE: /run/secrets/token
      MONGO_DB: doscuscope
      MONGO_HOST: mongo:27017
      MONGO_PASSWORD_FILE: /run/secrets/mongo_pass
      MONGO_USER_FILE: /run/secrets/mongo_user
      NODE_ENV: production
      ONTOPIC_SERVER: http://ontopic:5000/
      OPENAI_API_KEY_FILE: /run/secrets/openai_api_key
      PORT: 8888
      SCRIBE_TEMPLATES: /app/private/templates.json
      TOKEN_SECRET_FILE: /run/secrets/token
      WRITING_TASKS: /app/private/writing_tasks
    restart: always
    depends_on:
      - "mongo"
    volumes:
      - "./settings:/app/build/app/settings:ro"
      - "./private:/app/private:ro"

volumes:
  db_data:
    labels:
      edu.cmu.eberly.docuscope.description: "Database volume"

secrets:
  anthropic_api_key:
    file: secrets/anthropic_api_key
  mongo_user:
    file: secrets/mongo_user
  mongo_pass:
    file: secrets/mongo_pass
  openai_api_key:
    file: secrets/openai_api_key
  token:
    file: secrets/token
