export enum AccessDeniedReason {
  SERVER_DENY = 'DENIED BY SERVER SETTINGS',
  WRITING_TASK_DENY = 'DENIED BY WRITING TASK CONFIGURATION',
  SNAPSHOT_CONFIG_DENY = 'DENIED BY SNAPSHOT CONFIGURATION',
}
